# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# The following workflow will apply to both the frontend and backend of the project

name: Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Set up Node.js
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Install and test backend
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

#    - name: Run backend tests
#      run: |
#        cd backend
#        npm test

    # Install and test frontend
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

#    - name: Run frontend tests
#      run: |
#        cd frontend
#        npm test

    # Build the frontend
    - name: Build frontend
      run: |
        cd frontend
        npm run build